on:
    push:
        branches:
            - master
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: sudo apt install -y binutils-mipsel-linux-gnu
            - run: pipx install virtualenv
            - run: git fetch origin refs/encrypted-exe
            - run: git checkout FETCH_HEAD -- SCES_010.00.enc
            - run: openssl aes-256-cbc -pbkdf2 -d -k ${{ secrets.EXE_DECRYPTION_KEY }} < SCES_010.00.enc > SCES_010.00
            - run: make
